In [14]:
import pandas as pd

df = pd.read_csv("employment-rates.csv")
df.rename(columns={'Pacific Island Countries and territories':'island'}, inplace=True)
print(df.columns)
df = df[df["INDICATOR"]=="UNEMPRATE"]
df = df[df["Sex"].isin(["Male", "Female"])]
df = df[df["Age"].isin(["25-54", "55-64"])]
df = df[["island", "TIME_PERIOD", "OBS_VALUE", "Age", "Sex"]]
df.columns = ["island", "year", "unemployment_rate", "age", "sex"]
df.sort_values(by=["island", "year", "age", "sex"])

Index(['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'ACTION', 'FREQ',
       'Frequency', 'GEO_PICT', 'island', 'INDICATOR', 'Indicator', 'SEX',
       'Sex', 'AGE', 'Age', 'URBANIZATION', 'Urbanization', 'DISABILITY',
       'Disability', 'TIME_PERIOD', 'Time', 'OBS_VALUE', 'Observation value',
       'UNIT_MEASURE', 'Unit of measure', 'UNIT_MULT', 'Unit multiplier',
       'OBS_STATUS', 'Observation Status', 'DATA_SOURCE', 'Data source',
       'OBS_COMMENT', 'Comment', 'CONF_STATUS', 'Confidentiality status'],
      dtype='object')

                               island  year  unemployment_rate    age     sex
289                      Cook Islands  2015               1.44  25-54  Female
399                      Cook Islands  2015               1.71  25-54    Male
152                          Kiribati  2015              36.63  25-54  Female
327                          Kiribati  2015              24.70  25-54    Male
22                           Kiribati  2015              14.24  55-64  Female
186                          Kiribati  2015              12.52  55-64    Male
153                          Kiribati  2019               6.23  25-54  Female
328                          Kiribati  2019               5.97  25-54    Male
187                          Kiribati  2019               5.80  55-64    Male
197                  Marshall Islands  2011               1.00  25-54  Female
388                  Marshall Islands  2011               0.59  25-54    Male
198                  Marshall Islands  2019               4.18  25-54  Female
389                  Marshall Islands  2019               5.98  25-54    Male
234  Micronesia (Federated States of)  2013              21.84  25-54  Female
393  Micronesia (Federated States of)  2013              16.22  25-54    Male
14   Micronesia (Federated States of)  2013               5.85  55-64    Male
201                             Nauru  2011              33.50  25-54  Female
466                             Nauru  2011              19.05  25-54    Male
78                              Nauru  2011              21.59  55-64  Female
79                              Nauru  2011              18.90  55-64    Male
202                             Nauru  2012              14.81  25-54  Female
467                             Nauru  2012               8.85  25-54    Male
354                             Palau  2015               0.42  25-54  Female
116                             Palau  2015               0.70  25-54    Male
86                              Samoa  2013               2.00  25-54  Female
20                              Samoa  2013               1.01  25-54    Male
11                    Solomon Islands  2012               6.15  25-54  Female
81                    Solomon Islands  2012               4.75  25-54    Male
206                   Solomon Islands  2012               1.89  55-64    Male
375                             Tonga  2016               1.74  25-54  Female
107                             Tonga  2016               1.10  25-54    Male
456                             Tonga  2016               0.63  55-64    Male
376                             Tonga  2018               2.04  25-54  Female
108                             Tonga  2018               2.28  25-54    Male
377                             Tonga  2021               2.40  25-54  Female
109                             Tonga  2021               3.56  25-54    Male
27                             Tuvalu  2015              12.92  25-54  Female
102                            Tuvalu  2015              13.16  25-54    Male
223                            Tuvalu  2015              15.91  55-64    Male
28                             Tuvalu  2017              16.25  25-54  Female
103                            Tuvalu  2017              16.73  25-54    Male
404                            Tuvalu  2017               9.23  55-64  Female
224                            Tuvalu  2017              18.07  55-64    Male
168                           Vanuatu  2019               7.37  25-54  Female
459                           Vanuatu  2019               5.36  25-54    Male
284                           Vanuatu  2019               5.58  55-64  Female
339                           Vanuatu  2019               3.47  55-64    Male